//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildiMaterial.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderContent = new HashSet<OrderContent>();
        }
    
        public int ProductID { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public int UnitID { get; set; }
        public string Cost { get; set; }
        public string MaxSaleSize { get; set; }
        public int ManufacturerID { get; set; }
        public int SupplierID { get; set; }
        public int CategoryID { get; set; }
        public string CurrentDiscount { get; set; }
        public string AmountInStok { get; set; }
        public string Description { get; set; }
        public Nullable<int> Image { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Image Image1 { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderContent> OrderContent { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
