CREATE DATABASE BuildMateria1
GO
USE BuildMateria1
GO

CREATE TABLE [Role] (
  RoleID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  RoleName NVARCHAR(50) NOT NULL
)

CREATE TABLE [User] (
  UserID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  FirstName NVARCHAR (50) NOT NULL,
  LastName NVARCHAR (50) NOT NULL,
  MiddleName NVARCHAR (50) NOT NULL,
  UserLogin NVARCHAR(max) NOT NULL,
  UserPassword NVARCHAR(max) NOT NULL,
  UserRoleID INT FOREIGN KEY REFERENCES [Role](RoleID) NOT NULL
)

CREATE TABLE Client (
  ClientID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  UserID INT FOREIGN KEY REFERENCES [User](UserID) NOT NULL
)

CREATE TABLE City (
  CityID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  CityName NVARCHAR(50) NOT NULL
)

CREATE TABLE PickupPoint (
  PickupPointID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  MailIndex NVARCHAR(50) NOT NULL,
  CityID INT FOREIGN KEY REFERENCES [City](CityID) NOT NULL,
  Street NVARCHAR (50) NOT NULL,
  HousNumber NVARCHAR(50) NOT NULL
)

CREATE TABLE OrderStatus(
  OrderStatusID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  [Value] NVARCHAR(50) NOT NULL
)

CREATE TABLE [Order] (
  OrderID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  OrderDate DATE NOT NULL,
  [Date] DATE NOT NULL,
  ClientID INT FOREIGN KEY REFERENCES [Client](ClientID),
  PickupPointID INT FOREIGN KEY REFERENCES PickupPoint(PickupPointID) NOT NULL,
  Code NVARCHAR(50) NOT NULL,
  OrderStatusID INT FOREIGN KEY REFERENCES OrderStatus(OrderStatusID) NOT NULL
)

CREATE TABLE Category (
  CategoryID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  CategoryName NVARCHAR (50) NOT NULL
)

CREATE TABLE Unit (
  UnitID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  [Value] NVARCHAR(20) NOT NULL
)

CREATE TABLE Manufacturer (
  ManufacturerID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  ManufacturerName NVARCHAR (50) NOT NULL
)

CREATE TABLE Supplier (
  SupplierID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  SupplierName NVARCHAR(50) NOT NULL
)

CREATE Table [Image] (
  ImageID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  ImageName IMAGE NOT NULL
)
CREATE TABLE Product(
  ProductID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  Articul NVARCHAR(50) NOT NULL,
  [Name] NVARCHAR (50) NOT NULL,
  UnitID INT FOREIGN KEY REFERENCES Unit(UnitID) NOT NULL,
  Cost NVARCHAR (50) NOT NULL,
  MaxSaleSize NVARCHAR (50) NOT NULL,
  ManufacturerID INT FOREIGN KEY REFERENCES Manufacturer(ManufacturerID) NOT NULL,
  SupplierID INT FOREIGN KEY REFERENCES Supplier(SupplierID) NOT NULL,
  CategoryID INT FOREIGN KEY REFERENCES Category(CategoryID) NOT NULL,
  CurrentDiscount NVARCHAR(50) NOT NULL,
  AmountInStok NVARCHAR (50) NOT NULL,
  [Description] NVARCHAR(max) NOT NULL,
  [Image] INT FOREIGN KEY REFERENCES [Image](ImageID)
)

CREATE TABLE OrderContent (
  OrderContentID INT PRIMARY KEY IDENTITY(1,1)  NOT NULL,
  OredrID INT FOREIGN KEY REFERENCES [Order](OrderID) NOT NULL,
  ProductID INT FOREIGN KEY REFERENCES Product(ProductID) NOT NULL,
  Amount INT NOT NULL
)